# Uncomment this line to define a global platform for your project
# platform :ios, '8.1'

target 'Example' do
  pod 'ChatCenterSDK', :git => "https://github.com/chatcenter/ios.git"
  pod 'OpenTok'

  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Example

  target 'ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
